"""empty message

Revision ID: 20c5cbe1f3c7
Revises: 56c28cb24aca
Create Date: 2015-01-16 13:33:12.237792

"""

# revision identifiers, used by Alembic.
revision = '20c5cbe1f3c7'
down_revision = '56c28cb24aca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related',
    sa.Column('id_career', sa.Integer(), nullable=True),
    sa.Column('id_knowledge_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_career'], ['career.id'], ),
    sa.ForeignKeyConstraint(['id_knowledge_area'], ['knowledge_area.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related')
    ### end Alembic commands ###
