"""empty message

Revision ID: 26500f82293b
Revises: 45f717ed06d1
Create Date: 2015-01-09 01:41:42.025321

"""

# revision identifiers, used by Alembic.
revision = '26500f82293b'
down_revision = '45f717ed06d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('background', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'background')
    ### end Alembic commands ###
