"""empty message

Revision ID: 26e8f2d25636
Revises: 1f3a53ed4c90
Create Date: 2015-01-13 16:46:08.327784

"""

# revision identifiers, used by Alembic.
revision = '26e8f2d25636'
down_revision = '1f3a53ed4c90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related',
    sa.Column('id_career', sa.Integer(), nullable=True),
    sa.Column('id_knowledge_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_career'], ['career.id'], ),
    sa.ForeignKeyConstraint(['id_knowledge_area'], ['knowledge_area.id'], )
    )
    op.create_unique_constraint(None, 'knowledge_area', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_area', type_='unique')
    op.drop_table('related')
    ### end Alembic commands ###
