"""empty message

Revision ID: 272567270975
Revises: e594c100e34
Create Date: 2015-01-16 01:03:12.690850

"""

# revision identifiers, used by Alembic.
revision = '272567270975'
down_revision = 'e594c100e34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'knowledge_area', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_area', type_='unique')
    ### end Alembic commands ###
