"""empty message

Revision ID: 2c51fd57f367
Revises: 37d96de67d90
Create Date: 2015-01-16 13:22:35.144897

"""

# revision identifiers, used by Alembic.
revision = '2c51fd57f367'
down_revision = '37d96de67d90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related',
    sa.Column('id_career', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_knowledge_area', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_career'], [u'career.id'], name=u'related_id_career_fkey'),
    sa.ForeignKeyConstraint(['id_knowledge_area'], [u'knowledge_area.id'], name=u'related_id_knowledge_area_fkey')
    )
    ### end Alembic commands ###
