"""empty message

Revision ID: 36edc6e766f3
Revises: 2f699bf74d31
Create Date: 2015-01-16 17:52:09.308441

"""

# revision identifiers, used by Alembic.
revision = '36edc6e766f3'
down_revision = '2f699bf74d31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career', sa.Column('background', sa.Text(), nullable=True))
    op.add_column('career', sa.Column('icon', sa.Text(), nullable=True))
    op.add_column('universityheadquarter', sa.Column('background', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universityheadquarter', 'background')
    op.drop_column('career', 'icon')
    op.drop_column('career', 'background')
    ### end Alembic commands ###
