"""empty message

Revision ID: 382c02cc092d
Revises: 28f38cfa0895
Create Date: 2015-01-16 11:02:09.011582

"""

# revision identifiers, used by Alembic.
revision = '382c02cc092d'
down_revision = '28f38cfa0895'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related',
    sa.Column('id_career', sa.Integer(), nullable=True),
    sa.Column('id_knowledge_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_career'], ['career.id'], ),
    sa.ForeignKeyConstraint(['id_knowledge_area'], ['knowledge_area.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related')
    ### end Alembic commands ###
