"""empty message

Revision ID: 3b7e171c3bc4
Revises: 4efc165cc6af
Create Date: 2015-01-19 18:09:13.563220

"""

# revision identifiers, used by Alembic.
revision = '3b7e171c3bc4'
down_revision = '4efc165cc6af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_campus',
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['universityheadquarter.id'], ),
    sa.PrimaryKeyConstraint('src'),
    sa.UniqueConstraint('src')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_campus')
    ### end Alembic commands ###
