"""empty message

Revision ID: 4263c0c19011
Revises: 3eb41c049a05
Create Date: 2014-12-17 04:01:28.114204

"""

# revision identifiers, used by Alembic.
revision = '4263c0c19011'
down_revision = '3eb41c049a05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
