"""empty message

Revision ID: 4b96eac1a23
Revises: 283bab598eea
Create Date: 2015-01-14 18:25:07.319619

"""

# revision identifiers, used by Alembic.
revision = '4b96eac1a23'
down_revision = '283bab598eea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('accredited', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('university', sa.Column('facebook', sa.Text(), nullable=True))
    op.add_column('university', sa.Column('twitter', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'twitter')
    op.drop_column('university', 'facebook')
    op.drop_column('university', 'address')
    op.drop_column('university', 'accredited')
    ### end Alembic commands ###
