"""empty message

Revision ID: a378f17a932
Revises: 43c751bf31bc
Create Date: 2015-01-16 10:43:07.020504

"""

# revision identifiers, used by Alembic.
revision = 'a378f17a932'
down_revision = '43c751bf31bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
